---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mean
  namespace: default
  generation: 1
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mean
  template:
    metadata:
      name: mean
      creationTimestamp:
      labels:
        app: mean
    spec:
      containers:
      - name: mean
        image: nginx
        resources: {}
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        securityContext:
          privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
  - type: Available
    status: 'True'
    lastUpdateTime: '2018-03-06T09:03:59Z'
    lastTransitionTime: '2018-03-06T09:03:59Z'
    reason: MinimumReplicasAvailable
    message: Deployment has minimum availability.
  - type: Progressing
    status: 'True'
    lastUpdateTime: '2018-03-06T09:03:59Z'
    lastTransitionTime: '2018-03-06T09:03:54Z'
    reason: NewReplicaSetAvailable
    message: ReplicaSet "mean-657b4c98d4" has successfully progressed.
