apiVersion: v1
# --- 区分多个文件
kind: Pod
metadata:
  name: my-nginx
spec:
  replicas: 2
  template:
    metadata:
      name: my-nginx
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80