---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: pod
  namespace: default
  generation: 1
  labels:
    run: pod
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      run: pod
  template:
    metadata:
      creationTimestamp:
      labels:
        run: pod
    spec:
      containers:
      - name: pod
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
  - type: Available
    status: 'True'
    lastUpdateTime: '2018-03-08T10:36:01Z'
    lastTransitionTime: '2018-03-08T10:36:01Z'
    reason: MinimumReplicasAvailable
    message: Deployment has minimum availability.
