version: '2'
services:
    gitlab:
      image: 'twang2218/gitlab-ce-zh:10.6.2'
      restart: unless-stopped
      hostname: 'gitlab.sunmi.com'
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://gitlab.sunmi.com'
          gitlab_rails['time_zone'] = 'Asia/Shanghai'
          gitlab_rails['smtp_enable'] = true
          gitlab_rails['smtp_address'] = "smtp.sunmi.com"
          gitlab_rails['smtp_port'] = 465
          gitlab_rails['smtp_user_name'] = "service@sunmi.com"
          gitlab_rails['smtp_password'] = "Sunmi388{}"
          gitlab_rails['smtp_authentication'] = "login"
          gitlab_rails['smtp_enable_starttls_auto'] = true
          gitlab_rails['smtp_tls'] = true
          gitlab_rails['gitlab_email_from'] = 'service@sunmi.com'
      ports:
        - '10080:80'
        - '10443:443'
        - '22:22'
      volumes:
        - /app/gitlab/config/:/etc/gitlab
        - /app/gitlab/data/:/var/opt/gitlab
        - /app/gitlab/logs/:/var/log/gitlab
volumes:
    config:
    data:
    logs: