version: '3'

services:
  drone-server:
    image: drone/drone:0.8-alpine
    container_name: drone-server

    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - data:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_ADMIN=drone,mritd
      - DRONE_HOST=http://172.21.0.1/
      - DRONE_GITLAB=true
      - DRONE_GITLAB_PRIVATE_MODE=true
      - DRONE_GITLAB_URL=http://code.sunmi.com
      - DRONE_GITLAB_CLIENT=0cae7786c94dfbb49d55a9eaa1fcc4b5d99793dcdef6004e264d5624fae1d322
      - DRONE_GITLAB_SECRET=8a2f096e5f59ba172e4ec237ac7530437d46b500398931eeae86c284db4b803a
      - DRONE_SECRET=${DRONE_SECRET}

  drone-agent:
    image: drone/agent:0.8
    container_name: drone-agent
    command: agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER={DRONE_SERVER}
      - DRONE_SECRET=${DRONE_SECRET}

volumes:
  data: