apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-gitlab
  namespace: default
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 0372f48eb0-iik31.cn-hangzhou.nas.aliyuncs.com
    path: "/dev/file"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-gitlab
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi