clone:
  git:
    image: plugins/git

pipeline:
  deps:
    image: golang:latest
    commands:
      - go get
      - go test
  build:
    image: node:latest
    commands:
      - npm install
      - npm run test
      - npm run build