apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: server
    spec:
      containers:
      - name: server
        image: drone/drone:0.8
        imagePullPolicy: Always
        env:
          - name: "DRONE_HOST"
            value: http://drone.change.io/
          - name: "DRONE_OPEN"
            value: false
          - name: "DRONE_GITHUB"
            value: true
          - name: "DRONE_GITHUB_CLIENT"
            value: 8c3b141e8081d7858ec8
          - name: "DRONE_GITHUB_SECRET"
            value: 386a9f06fcbe3fc1b6ce0e022eceaaa4acc7e373
          - name: "DRONE_SECRET"
            value: XsJnj4DmzuXBKkcgHeUAJQxq
        volumeMounts:
        - mountPath: /var/lib/drone
          name: drone-lib
      volumes:
      - name: drone-lib
        hostPath:
          path: /var/lib/drone
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    name: server
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    name: server