#server用来处理任务分发
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drone-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: drone-server
    spec:
      containers:
      - name: drone-server
        image: drone/drone:0.8
        imagePullPolicy: Always
        env:
          - name: DRONE_HOST
            value: http://172.21.0.1/authorize
          - name: DRONE_OPEN
            value: "true"
          - name: DRONE_GITLAB
            value: true
          - name: DRONE_GITLAB_CLIENT
            value: 0cae7786c94dfbb49d55a9eaa1fcc4b5d99793dcdef6004e264d5624fae1d322
          - name: DRONE_GITLAB_SECRET
            value: 8a2f096e5f59ba172e4ec237ac7530437d46b500398931eeae86c284db4b803a
          - name: DRONE_SECRET
            value: {DRONE_SECRET}
        volumeMounts:
        - mountPath: /var/lib/drone
          name: file-drone
      volumes:
      - name: file-drone
        hostPath:
          # directory location on host
          path: /var/lib/drone
---
apiVersion: v1
kind: Service
metadata:
  name: drone-server
  labels:
    name: drone-server
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    name: drone-server